export const examples = [
    // Productive
    { text: "voce pode me enviar o cronograma atualizado do projeto", label: "Productive" },
    { text: "lembrete chamada com o cliente agendada para amanha as 10h", label: "Productive" },
    { text: "por favor revise o documento em anexo e forneca feedback", label: "Productive" },
    { text: "precisamos da sua aprovacao na proposta de orcamento", label: "Productive" },
    { text: "voce pode redefinir minha senha de acesso", label: "Productive" },
    { text: "o servidor esta fora do ar pode verificar isso com urgencia", label: "Productive" },
    { text: "preciso de esclarecimento sobre o item 3 do relatorio", label: "Productive" },
    { text: "por favor confirme sua presenca no workshop", label: "Productive" },
    { text: "voce pode atualizar o rastreador de issues com o status mais recente", label: "Productive" },
    { text: "precisamos da sua contribuicao para finalizar o contrato", label: "Productive" },
    { text: "enviei a minuta da ata da reuniao pode revisar ate o fim do dia", label: "Productive" },
    { text: "qual e a previsao de entrega da versao beta", label: "Productive" },
    { text: "por favor encaminhe os slides da apresentacao de ontem", label: "Productive" },
    { text: "voce pode confirmar se a fatura de setembro ja foi paga", label: "Productive" },
    { text: "atualizei a planilha de custos revise e valide os numeros", label: "Productive" },
    { text: "favor compartilhar a lista de participantes confirmados", label: "Productive" },
    { text: "o cliente solicitou alteracoes no contrato pode ajustar", label: "Productive" },
    { text: "marque uma reuniao de alinhamento com a equipe para amanha", label: "Productive" },
    { text: "envie o relatorio semanal ate as 17h de hoje", label: "Productive" },
    { text: "voce poderia me dar acesso ao repositorio privado", label: "Productive" },
    { text: "os testes automatizados falharam pode verificar o motivo", label: "Productive" },
    { text: "inclui comentarios no documento veja e ajuste conforme necessario", label: "Productive" },
    { text: "pode revisar a traducao do manual antes do envio ao cliente", label: "Productive" },
    { text: "qual e o status da integracao com o sistema externo", label: "Productive" },
    { text: "o prazo para envio do artigo e sexta ja finalizou sua parte", label: "Productive" },
    { text: "compartilhe comigo os acessos da conta corporativa", label: "Productive" },
    { text: "verifique se o backup do servidor foi concluido ontem", label: "Productive" },
    { text: "agende a call com os fornecedores para a proxima semana", label: "Productive" },
    { text: "atualize o jira com os tickets finalizados", label: "Productive" },
    { text: "pode revisar o orcamento da viagem e aprovar os custos", label: "Productive" },
    { text: "o contrato precisa da assinatura digital consegue finalizar hoje", label: "Productive" },
    { text: "gostaria de falar com voce hoje apos o almoco", label: "Productive" },
    { text: "encaminhe o email do cliente para o juridico revisar", label: "Productive" },
    { text: "voce pode preparar a pauta da reuniao de sexta", label: "Productive" },
    { text: "o bug reportado ontem ja foi corrigido", label: "Productive" },
    { text: "suba a versao corrigida no ambiente de homologacao", label: "Productive" },
    { text: "pode me enviar os acessos para o painel administrativo", label: "Productive" },
    { text: "favor revisar a lista de compras antes do envio", label: "Productive" },
    { text: "o cliente pediu atualizacao do cronograma consegue ajustar", label: "Productive" },
    { text: "anexe a documentacao no chamado de suporte", label: "Productive" },
    { text: "revise os calculos da planilha de orcamento", label: "Productive" },
    { text: "atualize os status dos leads no crm", label: "Productive" },
    { text: "pode revisar os slides e inserir os graficos", label: "Productive" },
    { text: "qual o prazo para entrega do relatorio trimestral", label: "Productive" },
    { text: "envie o documento assinado ainda hoje", label: "Productive" },
    { text: "crie um resumo executivo da apresentacao", label: "Productive" },
    { text: "confirme a reserva da sala de reuniao para amanha", label: "Productive" },
    { text: "verifique se todos receberam o convite do evento", label: "Productive" },
    { text: "pode revisar os anexos antes de enviarmos ao cliente", label: "Productive" },
    { text: "o deploy em producao sera hoje as 19h confirme se esta pronto", label: "Productive" },

    // Unproductive
    { text: "obrigado pela sua ajuda", "label": "Unproductive" },
    { text: "parabens por finalizar o projeto", "label": "Unproductive" },
    { text: "feliz aniversario", "label": "Unproductive" },
    { text: "bom trabalho na apresentacao de ontem", "label": "Unproductive" },
    { text: "adoro trabalhar com voce", "label": "Unproductive" },
    { text: "eu odeio segundas-feiras", "label": "Unproductive" },
    { text: "espero que tenha tido um otimo fim de semana", "label": "Unproductive" },
    { text: "bom trabalho continue assim", "label": "Unproductive" },
    { text: "so passando para dizer oi", "label": "Unproductive" },
    { text: "obrigado novamente", "label": "Unproductive" },
    { text: "voce tem interesse em comprar nosso produto", "label": "Unproductive" },
    { text: "confira nossa ultima promocao", "label": "Unproductive" },
    { text: "inscreva-se na nossa newsletter para receber novidades", "label": "Unproductive" },
    { text: "voce ja viu nosso novo post no blog", "label": "Unproductive" },
    { text: "temos uma oferta especial so para voce", "label": "Unproductive" },
    { text: "nao perca nosso proximo evento", "label": "Unproductive" },
    { text: "siga-nos nas redes sociais para mais conteudos", "label": "Unproductive" },
    { text: "vamos tomar um cafe qualquer dia", "label": "Unproductive" },
    { text: "quais sao seus planos para o fim de semana", "label": "Unproductive" },
    { text: "gostei muito da sua apresentacao parabens", "label": "Unproductive" },
    { text: "desejo sucesso na sua nova jornada", "label": "Unproductive" },
    { text: "boa sorte na entrevista amanha", "label": "Unproductive" },
    { text: "o clima hoje esta otimo", "label": "Unproductive" },
    { text: "esse meme me fez lembrar de voce", "label": "Unproductive" },
    { text: "queria compartilhar essa musica com voce", "label": "Unproductive" },
    { text: "voce viu o jogo ontem a noite", "label": "Unproductive" },
    { text: "esse filme novo e incrivel recomendo", "label": "Unproductive" },
    { text: "estou muito feliz com os resultados do time", "label": "Unproductive" },
    { text: "bom descanso para voce", "label": "Unproductive" },
    { text: "espero que melhore logo", "label": "Unproductive" },
    { text: "parabens pelo aniversario de casamento", "label": "Unproductive" },
    { text: "voce viu a nova cafeteria perto do escritorio", "label": "Unproductive" },
    { text: "olha so essa noticia curiosa", "label": "Unproductive" },
    { text: "saudades das nossas conversas", "label": "Unproductive" },
    { text: "boa viagem", "label": "Unproductive" },
    { text: "esse fim de semana promete", "label": "Unproductive" },
    { text: "desejo que tenha um otimo feriado", "label": "Unproductive" },
    { text: "acabei de comprar um celular novo", "label": "Unproductive" },
    { text: "estou muito animado para o show de sabado", "label": "Unproductive" },
    { text: "bom dia como voce esta", "label": "Unproductive" },
    { text: "boa noite durma bem", "label": "Unproductive" },
    { text: "voce gosta de pizza", "label": "Unproductive" },
    { text: "gostaria de marcar um almoco sem compromisso", "label": "Unproductive" },
    { text: "olha essa promocao de passagens aereas", "label": "Unproductive" },
    { text: "espero que tenha gostado do presente", "label": "Unproductive" },
    { text: "boa sorte no campeonato", "label": "Unproductive" },
    { text: "esse restaurante e muito bom recomendo", "label": "Unproductive" },
    { text: "adorei a foto que voce postou", "label": "Unproductive" },
    { text: "essa piada e otima tinha que compartilhar", "label": "Unproductive" },
    { text: "feliz ano novo", "label": "Unproductive" },
    { text: "boas festas para voce e sua familia", "label": "Unproductive" }
];

export const replies = [
    { trigger: /cronograma|agenda|reuniao|chamada/, reply: "Vou verificar a agenda e confirmar." },
    { trigger: /relatorio|documento|feedback/, reply: "Vou revisar e fornecer feedback." },
    { trigger: /aprovacao|orcamento|contrato/, reply: "Vou revisar e aprovar se estiver tudo certo." },
    { trigger: /senha|conta|acesso/, reply: "Vou redefinir e enviar os dados de acesso." },
    { trigger: /servidor|erro|problema|bug/, reply: "Vou investigar o problema e atualizar você." },
    { trigger: /confirmar|presenca/, reply: "Confirmo minha presença." },
    { trigger: /permissao|repositorio|acessos/, reply: "Vou liberar o acesso solicitado." },
    { trigger: /fatura|pagamento|cobranca/, reply: "Vou confirmar o status do pagamento." },
    { trigger: /slides|apresentacao/, reply: "Vou revisar os slides e ajustar se necessário." },
    { trigger: /backup|implantacao|publicacao/, reply: "Vou acompanhar o processo e garantir que ocorra bem." }
];